FROM ubuntu:jammy
MAINTAINER jwstar
ENV DEBIAN_FRONTEND=noninteractive

RUN  apt-get -y update  \
    && apt-get install -y --no-install-recommends \
     python3.11 python3-pip python3.11-dev nodejs

WORKDIR /workspaces

COPY requirements.txt ./

RUN pip3 --no-cache-dir install --user -r requirements.txt
